# example values
server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    username: root
    password: mysql1!
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


indexing-settings:
  sites:
    - url: http://www.playback.ru/
      name: PlayBack.Ru
    - url: https://skillbox.ru/
      name: Skillbox
#    - url: https://ipfran.ru/
#     name: Ipfan
#    - url: https://dombulgakova.ru/
#     name: dombulgakova

